apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zero-trust-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: zero-trust
  
  source:
    repoURL: git@github.com:YOUR_ORG/zero_trust.git
    targetRevision: main
    path: kubernetes/overlays/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: workloads
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
